name: taienv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - faiss-gpu
  - pip
  - pip:
    - torch>=2.0
    - tokenizers>=0.14.0
    - transformers>=4.35.0
    - accelerate
    - sympy==1.12
    - pebble
    - timeout-decorator
    - attrdict

