name: taienv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss-cpu=1.7.3
  - pip
  - setuptools
  - libblas
  - openblas
  - nomkl
  - ipykernel
  - pip:
    - torch>=2.0
    - tokenizers>=0.14.0
    - transformers>=4.35.0
    - accelerate
    - sympy==1.12
    - pebble
    - timeout-decorator
    - attrdict
    - langchain
    - langchain-community
    - pypdf
    

